### ISSUE TITLE
Migration to version 16.0

### ISSUE THREAD

**Issue by sbidoul** [OCA/brand#130]
# Todo

https://github.com/OCA/maintainer-tools/wiki/Migration-to-version-16.0

# Modules to migrate

- [x] account_brand, @sbejaoui #131 
- [ ] analytic_brand
- [x] brand, @sbejaoui #131 
- [x] brand_external_report_layout @sbejaoui #133 
- [ ] contract_brand
- [x] product_brand - By @marielejeune - #132
- [x] sale_brand, @sbejaoui #134 
- [x] stock_brand - By @edescalona - #256

Missing module? Check https://github.com/OCA/maintainer-tools/wiki/%5BFAQ%5D-Missing-modules-in-migration-issue-list

**Comment by sbejaoui** [comment]
brand, account_brand #131

**Comment by sbejaoui** [comment]
brand_external_report_layout #133

**Comment by francesco-ooops** [comment]
@sbejaoui can you pin this issue?

**Comment by SergioPSV** [comment]
pricelist_brand https://github.com/OCA/brand/pull/164

**Comment by OpenCode** [comment]
product_brand_purchase from 14.0 https://github.com/OCA/brand/pull/171

**Comment by edescalona** [comment]
Start migration stock_brand 

PR #256

**Comment by pcastelovigo** [comment]
analytic_brand PR #283

**Comment by pcastelovigo** [comment]
contract_brand PR #285

**Comment by pcastelovigo** [comment]
@sbidoul could this issue be closed?
